---
title: "plotting"
author: "Alex Xiaotong Gui"
date: "7/24/2018"
output: html_document
---

```{r}
library(readr)
# read in the scanner data
folder <- "~/Documents/School/DIMACS REU/measurements/scanner-data/"
file_list <- list.files(path = folder, pattern = "*.obj")

scannerdf<-data.frame()
for (i in 1:length(file_list)){
  scanner<-read_delim(paste(folder, file_list[i],sep='')," ", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE, skip = 3)[,-1]
  name<-paste("scanner-",substr(file_list[i],start=1,stop=nchar(file_list[i])-4),sep ='')
  assign(name, scanner) 
  
  X<-scanner$X2
  Y<-scanner$X3
  Z<-scanner$X4
  
  # trim X, Y and Z that are out of range
  Y<-Y[which(abs(X)<=35)]
  Z<-Z[which(abs(X)<=35)]
  X<-X[which(abs(X)<=35)]

  X<-X[which(abs(Y)<=35)]
  Z<-Z[which(abs(Y)<=35)]
  Y<-Y[which(abs(Y)<=35)]
  
  # put Z of each sample into the rows of the df
  scannerdf<-rbind(scannerdf,Z)
}

scannerdf[is.na(scannerdf)]<-0
```

```{r}
scanner_mat<-as.matrix(scannerdf)
scanner_pca<-prcomp(scanner_mat,center=TRUE)
write.csv(scanner_pca$x[,1:4],"scanner_pca.csv")
```







